Repository anwilli5/coin-collection-android-US, pull requests merged in 2022-10, with the labels that each got.

#88 Added feature request template
  .github/ISSUE_TEMPLATE/feature_request_template.yaml
Labels: hacktoberfest-accepted

#84 Updating screenshots and adding screenshot collection
  app/src/test/data/coin-collection-screenshots.json
  images/screenshots/large/coin_actions_screen.png
  images/screenshots/large/collection_creation_screen.png
  images/screenshots/large/lincoln_cents_screen.png
  images/screenshots/large/main_screen.png
  images/screenshots/large/morgan_dollars_screen.png
  images/screenshots/large/presidential_dollars_screen.png
  images/screenshots/medium/coin_actions_screen.png
  images/screenshots/medium/collection_creation_screen.png
  images/screenshots/medium/lincoln_cents_screen.png
  images/screenshots/medium/main_screen.png
  images/screenshots/medium/morgan_dollars_screen.png
  images/screenshots/medium/presidential_dollars_screen.png
  images/screenshots/small/coin_actions_screen.png
  images/screenshots/small/collection_creation_screen.png
  images/screenshots/small/lincoln_cents_screen.png
  images/screenshots/small/main_screen.png
  images/screenshots/small/morgan_dollars_screen.png
  images/screenshots/small/presidential_dollars_screen.png
Labels: hacktoberfest-accepted, hacktoberfest

#89 Updating gradle version
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .project
  app/.project
  app/build.gradle
  app/src/androidTest/AndroidManifest.xml
  app/src/main/AndroidManifest.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: hacktoberfest-accepted

#91 Adding code to fix any possible SQL injections
  app/src/main/java/com/coincollection/DatabaseAdapter.java
  app/src/main/java/com/coincollection/DatabaseHelper.java
Labels: hacktoberfest-accepted, hacktoberfest

#93 Create SECURITY.md
  SECURITY.md
Labels: hacktoberfest

#94 Updating dependency versions (including CSV library)
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/coincollection/ExportImportHelper.java
  app/src/sharedTest/java/com/spencerpages/SharedTest.java
  app/src/test/java/ExportImportTests.java
Labels: hacktoberfest
